import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_PATH = os.getenv("DATABASE_PATH")
EBAY_WEBHOOK_URL = os.getenv("EBAY_WEBHOOK_URL")
POSHMARK_WEBHOOK_URL = os.getenv("POSHMARK_WEBHOOK_URL")
OHORA_DISNEY_JP_WEBHOOK_URL = os.getenv("OHORA_DISNEY_JP_WEBHOOK_URL")
OHORA_JP_WEBHOOK_URL = os.getenv("OHORA_JP_WEBHOOK_URL")
OHORA_WEBHOOK_URL = os.getenv("OHORA_WEBHOOK_URL")
MERCARI_WEBHOOK_URL = os.getenv("MERCARI_WEBHOOK_URL")
