import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_PATH = os.getenv("DATABASE_PATH")
EBAY_WEBHOOK_URL = os.getenv("EBAY_WEBHOOK_URL")
POSHMARK_WEBHOOK_URL = os.getenv("POSHMARK_WEBHOOK_URL")
OHORA_DISNEY_JP_WEBHOOK_URL = os.getenv("OHORA_DISNEY_JP_WEBHOOK_URL")
OHORA_JP_WEBHOOK_URL = os.getenv("OHORA_JP_WEBHOOK_URL")
OHORA_WEBHOOK_URL = os.getenv("OHORA_WEBHOOK_URL")
MERCARI_WEBHOOK_URL = os.getenv("MERCARI_WEBHOOK_URL")
SEVEN_NANA_WEBHOOK_URL = os.getenv("SEVEN_NANA_WEBHOOK_URL")
COSME_WEBHOOK_URL = os.getenv("COSME_WEBHOOK_URL")
DASHINGDIVA_WEBHOOK_URL = os.getenv("DASHINGDIVA_WEBHOOK_URL")
ESSHIMO_WEBHOOK_URL = os.getenv("ESSHIMO_WEBHOOK_URL")

# Store API configuration
BACKEND_URL = os.getenv("BACKEND_URL")
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD")
